
apiVersion: v1
kind: Secret
metadata:
  name: smtp-secret
  labels:
    app: retofit
type: Opaque
data:
  MAIL_SERVER: c210cC5nbWFpbC5jb20=
  MAIL_PORT: NTg3
  MAIL_USERNAME: cmV0b2ZpdGFwcEBnbWFpbC5jb20=
  MAIL_PASSWORD: dWJpZCBqcXVsIG16bWcgbm53aA==
  MAIL_FROM: cmV0b2ZpdGFwcEBnbWFpbC5jb20=
  MAIL_USE_TLS: dHJ1ZQ==
  MAIL_USE_SSL: ZmFsc2U=
